version: '2'
services: 
 elastic:
  image: elasticsearch
  ports:
   - 9200:9200
   - 9300:9300
 happyeyeserver: 
  build: ./happyeyeserver/.
  environment:
   - PORT=3000
   - ELASTICURL=elastic:9200
  ports: 
   - 3000:3000
  links:
   - elastic:elastic
 happysensor: 
  build: ./happysensor/.
  ports: 
   - 80:80
 kibana:
  image: kibana
  environment:
   - ELASTICSEARCH_URL=http://elastic:9200
  ports:
   - 5601:5601
  links:
   - elastic:elastic

